import {
  AGENT_TASKS,
  ARTIFACTS,
  BUILT_IN_AGENT_TEMPLATES,
  COPILOT_MODEL_OPTIONS,
  EXECUTION_LOGS,
  LEARNING_UPDATES,
  WORKFLOWS,
  WORK_ITEMS,
  getStandardAgentContract,
} from '../src/constants';
import {
  AgentOutputRecord,
  AgentLearningProfile,
  AgentTask,
  Capability,
  CapabilityAgent,
  CapabilityChatMessage,
  CapabilityWorkspace,
  ExecutionLog,
  LearningUpdate,
  WorkItem,
  Workflow,
} from '../src/types';
import {
  getLegacyArtifactListsFromContract,
  normalizeAgentOperatingContract,
  normalizeAgentLearningProfile,
  normalizeAgentRoleStarterKey,
  normalizeAgentSessionSummary,
  normalizeLearningUpdate,
} from '../src/lib/agentRuntime';
import { buildCapabilityBriefing } from '../src/lib/capabilityBriefing';
import { WORKSPACE_AGENT_TEMPLATES } from '../src/lib/workspaceFoundations';

const DEFAULT_AGENT_PROVIDER = 'GitHub Copilot SDK' as const;
const DEFAULT_AGENT_MODEL = COPILOT_MODEL_OPTIONS[0].id;
const DEFAULT_AGENT_TOKEN_LIMIT = 12000;
const COLLECTION_BUILT_IN_AGENT_KEYS: Set<string> = new Set([
  'PLANNING',
  'ARCHITECT',
  'BUSINESS-ANALYST',
  'VALIDATION',
] as const);

export const createDefaultAgentLearningProfile = (): AgentLearningProfile => ({
  status: 'NOT_STARTED',
  summary: '',
  highlights: [],
  contextBlock: '',
  sourceDocumentIds: [],
  sourceArtifactIds: [],
  sourceCount: 0,
});

const slugify = (value: string) =>
  value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 24);

const getCapabilityDocumentationSources = (capability: Capability) =>
  [capability.confluenceLink, capability.jiraBoardLink, capability.documentationNotes].filter(
    Boolean,
  ) as string[];

const toAgentLabel = (value: string) =>
  value
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, char => char.toUpperCase());

const getAgentTemplate = (key: string) =>
  WORKSPACE_AGENT_TEMPLATES.find(template => template.key === key);

const getAvailableCapabilitySkillIds = (capability: Capability) =>
  new Set(capability.skillLibrary.map(skill => skill.id));

const getDefaultSkillIds = (capability: Capability, templateKey?: string) => {
  const availableSkills = getAvailableCapabilitySkillIds(capability);
  const template = getAgentTemplate(templateKey || 'OWNER');
  const preferred = (template?.defaultSkillIds || []).filter(skillId =>
    availableSkills.has(skillId),
  );

  return preferred.length > 0
    ? preferred
    : capability.skillLibrary.map(skill => skill.id);
};

const getPreferredToolIds = (templateKey: string = 'OWNER') => [
  ...(getAgentTemplate(templateKey || 'OWNER')?.preferredToolIds || []),
];

const createBuiltInAgentId = (capabilityId: string, key: string) =>
  `AGENT-${slugify(capabilityId)}-${key}`;

const resolveCapabilityText = (value: string, capability: Capability) =>
  value.replace(/\{capabilityName\}/g, capability.name);

const getBuiltInTemplatesForCapability = (capability: Capability) =>
  BUILT_IN_AGENT_TEMPLATES.filter(template =>
    capability.capabilityKind === 'COLLECTION'
      ? COLLECTION_BUILT_IN_AGENT_KEYS.has(template.key)
      : true,
  );

const getMetadataNumber = (value: unknown) =>
  typeof value === 'number' && Number.isFinite(value) ? value : undefined;

export const buildPreviousOutputs = (
  capabilityId: string,
  agentId: string,
  tasks: AgentTask[] = AGENT_TASKS,
  logs: ExecutionLog[] = EXECUTION_LOGS,
): AgentOutputRecord[] => {
  const taskOutputs = tasks
    .filter(task => task.capabilityId === capabilityId && task.agent === agentId)
    .flatMap(task =>
      (task.producedOutputs || []).map((output, index) => ({
        id: `${task.id}-OUT-${index + 1}`,
        title: output.name,
        summary: `${task.title} output generated by ${toAgentLabel(agentId)}.`,
        timestamp: task.timestamp,
        status: output.status,
        relatedTaskId: task.id,
      })),
    );

  const loggedOutputs = logs
    .filter(log => log.capabilityId === capabilityId && log.agentId === agentId)
    .flatMap(log => {
      const outputTitle =
        typeof log.metadata?.outputTitle === 'string' ? log.metadata.outputTitle : undefined;
      const outputSummary =
        typeof log.metadata?.outputSummary === 'string'
          ? log.metadata.outputSummary
          : undefined;

      if (!outputTitle && !outputSummary) {
        return [];
      }

      return [
        {
          id: `${log.id}-OUT`,
          title: outputTitle || 'Capability response',
          summary: outputSummary || log.message,
          timestamp: log.timestamp,
          status:
            log.metadata?.outputStatus === 'pending' ? 'pending' : 'completed',
          artifactId:
            typeof log.metadata?.artifactId === 'string' ? log.metadata.artifactId : undefined,
        } satisfies AgentOutputRecord,
      ];
    });

  return [...loggedOutputs, ...taskOutputs];
};

export const buildAgentUsage = (
  capabilityId: string,
  agentId: string,
  tasks: AgentTask[] = AGENT_TASKS,
  logs: ExecutionLog[] = EXECUTION_LOGS,
) => {
  const relatedTasks = tasks.filter(
    task => task.capabilityId === capabilityId && task.agent === agentId,
  );
  const relatedLogs = logs.filter(
    log => log.capabilityId === capabilityId && log.agentId === agentId,
  );
  const logsWithUsage = relatedLogs.filter(log =>
    getMetadataNumber(log.metadata?.totalTokens) !== undefined ||
    getMetadataNumber(log.metadata?.promptTokens) !== undefined ||
    getMetadataNumber(log.metadata?.completionTokens) !== undefined,
  );
  const logsWithoutUsageCount = relatedLogs.length - logsWithUsage.length;
  const taskPromptTokens = relatedTasks.reduce(
    (count, task) => count + Math.max(320, (task.prompt || '').length * 2),
    0,
  );
  const taskCompletionTokens = relatedTasks.reduce(
    (count, task) => count + (task.producedOutputs?.length || 0) * 280 + 160,
    0,
  );
  const promptTokens =
    taskPromptTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.promptTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 48;
  const completionTokens =
    taskCompletionTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.completionTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 36;
  const totalTokens = promptTokens + completionTokens;
  const requestCount =
    logsWithUsage.length > 0
      ? relatedTasks.length + logsWithUsage.length
      : Math.max(relatedLogs.length, relatedTasks.length);

  return {
    requestCount,
    promptTokens,
    completionTokens,
    totalTokens,
    estimatedCostUsd: Number((totalTokens * 0.000003).toFixed(4)),
    lastRunAt: relatedLogs[relatedLogs.length - 1]?.timestamp || relatedTasks[0]?.timestamp,
  };
};

export const applyWorkspaceRuntime = (
  capability: Capability,
  agents: CapabilityAgent[],
  tasks: AgentTask[],
  logs: ExecutionLog[],
): CapabilityAgent[] =>
  agents.map(agent => ({
    ...agent,
    capabilityId: capability.id,
    roleStarterKey:
      normalizeAgentRoleStarterKey(agent.roleStarterKey) ||
      normalizeAgentRoleStarterKey(agent.isOwner ? 'OWNER' : agent.standardTemplateKey),
    contract: normalizeAgentOperatingContract(agent.contract, {
      description: agent.objective || agent.role,
      suggestedInputArtifacts: agent.inputArtifacts,
      expectedOutputArtifacts: agent.outputArtifacts,
    }),
    ...getLegacyArtifactListsFromContract(
      normalizeAgentOperatingContract(agent.contract, {
        description: agent.objective || agent.role,
        suggestedInputArtifacts: agent.inputArtifacts,
        expectedOutputArtifacts: agent.outputArtifacts,
      }),
    ),
    skillIds:
      agent.skillIds?.length
        ? agent.skillIds
        : getDefaultSkillIds(capability, agent.isOwner ? 'OWNER' : agent.standardTemplateKey),
    preferredToolIds:
      agent.preferredToolIds?.length
        ? agent.preferredToolIds
        : getPreferredToolIds(agent.isOwner ? 'OWNER' : agent.standardTemplateKey),
    provider: agent.provider || DEFAULT_AGENT_PROVIDER,
    model: agent.model || DEFAULT_AGENT_MODEL,
    tokenLimit: agent.tokenLimit || DEFAULT_AGENT_TOKEN_LIMIT,
    learningProfile: normalizeAgentLearningProfile(
      agent.learningProfile || createDefaultAgentLearningProfile(),
    ),
    sessionSummaries: (agent.sessionSummaries || []).map(summary =>
      normalizeAgentSessionSummary(summary),
    ),
    usage: buildAgentUsage(capability.id, agent.id, tasks, logs),
    previousOutputs: buildPreviousOutputs(capability.id, agent.id, tasks, logs),
  }));

export const buildOwnerAgent = (capability: Capability): CapabilityAgent => {
  const ownerAgentId =
    capability.specialAgentId ||
    `AGENT-${slugify(capability.name || capability.id || 'CAPABILITY')}-OWNER`;

  return {
    id: ownerAgentId,
    capabilityId: capability.id,
    name: 'Capability Owning Agent',
    role: 'Capability Owner',
    roleStarterKey: 'OWNER',
    objective: `Own the end-to-end delivery context for ${capability.name} and coordinate all downstream agents within this capability.`,
    systemPrompt: `You are the capability owner for ${capability.name}. Ground every decision, workflow, and team action in the capability's domain, documentation, and governance context.`,
    contract: getStandardAgentContract('OWNER'),
    initializationStatus: 'READY',
    documentationSources: getCapabilityDocumentationSources(capability),
    ...getLegacyArtifactListsFromContract(getStandardAgentContract('OWNER')),
    isOwner: true,
    learningNotes: [
      `${capability.name} team context is isolated to this capability.`,
      `All downstream chats, agents, and workflows should remain aligned to ${capability.domain || capability.name}.`,
    ],
    skillIds: getDefaultSkillIds(capability, 'OWNER'),
    preferredToolIds: getPreferredToolIds('OWNER'),
    provider: DEFAULT_AGENT_PROVIDER,
    model: DEFAULT_AGENT_MODEL,
    tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
    learningProfile: createDefaultAgentLearningProfile(),
    sessionSummaries: [],
    usage: buildAgentUsage(capability.id, ownerAgentId, [], []),
    previousOutputs: [],
  };
};

export const buildBuiltInAgents = (capability: Capability): CapabilityAgent[] =>
  getBuiltInTemplatesForCapability(capability).map(template => {
    const agentId = createBuiltInAgentId(capability.id, template.key);

    return {
      id: agentId,
      capabilityId: capability.id,
      name: template.name,
      role: template.role,
      roleStarterKey: template.roleStarterKey,
      objective: resolveCapabilityText(template.objective, capability),
      systemPrompt: resolveCapabilityText(template.systemPrompt, capability),
      contract: template.contract,
      initializationStatus: 'READY',
      documentationSources: getCapabilityDocumentationSources(capability),
      ...getLegacyArtifactListsFromContract(template.contract),
      isBuiltIn: true,
      standardTemplateKey: template.key,
      learningNotes: [
        `${template.name} is a built-in agent for ${capability.name}.`,
        `Keep all outputs aligned to ${capability.domain || capability.name} capability context.`,
      ],
      skillIds: getDefaultSkillIds(capability, template.key),
      preferredToolIds: getPreferredToolIds(template.key),
      provider: DEFAULT_AGENT_PROVIDER,
      model: DEFAULT_AGENT_MODEL,
      tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
      learningProfile: createDefaultAgentLearningProfile(),
      sessionSummaries: [],
      usage: buildAgentUsage(capability.id, agentId, [], []),
      previousOutputs: [],
    };
  });

export const buildBaseAgents = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityAgent[] => [ownerAgent, ...buildBuiltInAgents(capability)];

const mergeWorkspaceAgents = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
  agents: CapabilityAgent[],
  tasks: AgentTask[],
  logs: ExecutionLog[],
) => {
  const builtInAgents = buildBuiltInAgents(capability);
  const builtInIds = new Set(builtInAgents.map(agent => agent.id));
  const builtInTemplateKeys = new Set(
    builtInAgents
      .map(agent => agent.standardTemplateKey)
      .filter(Boolean),
  );
  const nextOwnerAgent: CapabilityAgent = {
    ...buildOwnerAgent(capability),
    ...ownerAgent,
    capabilityId: capability.id,
    isOwner: true,
  };

  return applyWorkspaceRuntime(
    capability,
    [
      nextOwnerAgent,
      ...builtInAgents.map(agent => {
        const existingAgent = agents.find(
          current => !current.isOwner && current.id === agent.id,
        );

        return existingAgent
          ? {
              ...agent,
              ...existingAgent,
              capabilityId: capability.id,
              isBuiltIn: true,
            }
          : agent;
      }),
      ...agents
        .filter(agent => !agent.isOwner && !builtInIds.has(agent.id))
        .filter(
          agent =>
            !agent.isBuiltIn ||
            !agent.standardTemplateKey ||
            builtInTemplateKeys.has(agent.standardTemplateKey),
        ),
    ],
    tasks,
    logs,
  );
};

export const buildWelcomeMessage = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityChatMessage => ({
  id: `MSG-${capability.id}-WELCOME`,
  capabilityId: capability.id,
  role: 'agent',
  content: `I am the Capability Owning Agent for ${capability.name}. Everything in this workspace now belongs to this capability context, including team formation, learning, workflows, and chat.`,
  timestamp: 'Just now',
  agentId: ownerAgent.id,
  agentName: ownerAgent.name,
});

export const buildSeededAgents = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityAgent[] => {
  const nextAgents = new Map<string, CapabilityAgent>(
    buildBuiltInAgents(capability).map(agent => [agent.id, agent]),
  );
  const learningByAgent = LEARNING_UPDATES.filter(
    update => update.capabilityId === capability.id,
  ).reduce<Record<string, string[]>>((acc, update) => {
    acc[update.agentId] = [...(acc[update.agentId] || []), update.insight];
    return acc;
  }, {});

  const registerAgent = (agentId?: string | null, role = 'Capability Agent') => {
    if (!agentId || agentId === ownerAgent.id || nextAgents.has(agentId)) {
      return;
    }

    const outputArtifacts = ARTIFACTS.filter(
      artifact =>
        artifact.capabilityId === capability.id &&
        (artifact.connectedAgentId === agentId || artifact.agent === agentId),
    ).map(artifact => artifact.name);
    const contract = normalizeAgentOperatingContract(undefined, {
      description: `Execute ${capability.name} work inside this capability context and hand off outputs to the next workflow stage.`,
      expectedOutputArtifacts: outputArtifacts,
    });
    const legacyArtifacts = getLegacyArtifactListsFromContract(contract);

    nextAgents.set(agentId, {
      id: agentId,
      capabilityId: capability.id,
      name: toAgentLabel(agentId),
      role,
      roleStarterKey: 'EXECUTION-OPS',
      objective: `Execute ${capability.name} work inside this capability context and hand off outputs to the next workflow stage.`,
      systemPrompt: `You are a ${role.toLowerCase()} for ${capability.name}. Stay inside this capability's metadata, documentation, workflows, and learning context.`,
      contract,
      initializationStatus: 'READY',
      documentationSources: getCapabilityDocumentationSources(capability),
      inputArtifacts: legacyArtifacts.inputArtifacts,
      outputArtifacts: legacyArtifacts.outputArtifacts,
      learningNotes: learningByAgent[agentId] || [],
      skillIds: getDefaultSkillIds(capability),
      preferredToolIds: [],
      provider: DEFAULT_AGENT_PROVIDER,
      model: DEFAULT_AGENT_MODEL,
      tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
      learningProfile: createDefaultAgentLearningProfile(),
      sessionSummaries: [],
      usage: buildAgentUsage(capability.id, agentId),
      previousOutputs: buildPreviousOutputs(capability.id, agentId),
    });
  };

  WORKFLOWS.filter(workflow => workflow.capabilityId === capability.id).forEach(workflow => {
    workflow.steps.forEach(step => registerAgent(step.agentId, 'Workflow Agent'));
  });
  AGENT_TASKS.filter(task => task.capabilityId === capability.id).forEach(task =>
    registerAgent(task.agent, 'Task Agent'),
  );
  ARTIFACTS.filter(artifact => artifact.capabilityId === capability.id).forEach(artifact =>
    registerAgent(artifact.connectedAgentId || artifact.agent, 'Artifact Agent'),
  );
  WORK_ITEMS.filter(item => item.capabilityId === capability.id).forEach(item =>
    registerAgent(item.assignedAgentId, 'Delivery Agent'),
  );
  EXECUTION_LOGS.filter(log => log.capabilityId === capability.id).forEach(log =>
    registerAgent(log.agentId, 'Execution Agent'),
  );

  return [ownerAgent, ...nextAgents.values()];
};

export const materializeWorkspace = (
  capability: Capability,
  workspace: {
    capabilityId: string;
    agents: CapabilityAgent[];
    workflows: Workflow[];
    artifacts: CapabilityWorkspace['artifacts'];
    tasks: AgentTask[];
    executionLogs: ExecutionLog[];
    learningUpdates: LearningUpdate[];
    workItems: WorkItem[];
    messages: CapabilityChatMessage[];
    activeChatAgentId?: string;
    createdAt: string;
  },
): CapabilityWorkspace => {
  const ownerAgent =
    workspace.agents.find(agent => agent.isOwner) || buildOwnerAgent(capability);
  const agents = mergeWorkspaceAgents(
    capability,
    ownerAgent,
    workspace.agents,
    workspace.tasks,
    workspace.executionLogs,
  );

  return {
    capabilityId: capability.id,
    briefing: buildCapabilityBriefing(capability),
    agents,
    workflows: workspace.workflows,
    artifacts: workspace.artifacts,
    tasks: workspace.tasks,
    executionLogs: workspace.executionLogs,
    learningUpdates: workspace.learningUpdates.map(update =>
      normalizeLearningUpdate(update),
    ),
    workItems: workspace.workItems,
    messages:
      workspace.messages.length > 0
        ? workspace.messages
        : [buildWelcomeMessage(capability, ownerAgent)],
    activeChatAgentId:
      workspace.activeChatAgentId &&
      agents.some(agent => agent.id === workspace.activeChatAgentId)
        ? workspace.activeChatAgentId
        : ownerAgent.id,
    createdAt: workspace.createdAt,
  };
};
