import {
  AGENT_TASKS,
  ARTIFACTS,
  COPILOT_MODEL_OPTIONS,
  EXECUTION_LOGS,
  LEARNING_UPDATES,
  WORKFLOWS,
  WORK_ITEMS,
} from '../src/constants';
import {
  AgentOutputRecord,
  AgentTask,
  Capability,
  CapabilityAgent,
  CapabilityChatMessage,
  CapabilityWorkspace,
  ExecutionLog,
  LearningUpdate,
  WorkItem,
  Workflow,
} from '../src/types';

const DEFAULT_AGENT_PROVIDER = 'GitHub Copilot API' as const;
const DEFAULT_AGENT_MODEL = COPILOT_MODEL_OPTIONS[0].id;
const DEFAULT_AGENT_TOKEN_LIMIT = 12000;

const slugify = (value: string) =>
  value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 24);

const getCapabilityDocumentationSources = (capability: Capability) =>
  [capability.confluenceLink, capability.jiraBoardLink, capability.documentationNotes].filter(
    Boolean,
  ) as string[];

const toAgentLabel = (value: string) =>
  value
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, char => char.toUpperCase());

const getDefaultSkillIds = (capability: Capability) =>
  capability.skillLibrary.map(skill => skill.id);

const getMetadataNumber = (value: unknown) =>
  typeof value === 'number' && Number.isFinite(value) ? value : undefined;

export const buildPreviousOutputs = (
  capabilityId: string,
  agentId: string,
  tasks: AgentTask[] = AGENT_TASKS,
  logs: ExecutionLog[] = EXECUTION_LOGS,
): AgentOutputRecord[] => {
  const taskOutputs = tasks
    .filter(task => task.capabilityId === capabilityId && task.agent === agentId)
    .flatMap(task =>
      (task.producedOutputs || []).map((output, index) => ({
        id: `${task.id}-OUT-${index + 1}`,
        title: output.name,
        summary: `${task.title} output generated by ${toAgentLabel(agentId)}.`,
        timestamp: task.timestamp,
        status: output.status,
        relatedTaskId: task.id,
      })),
    );

  const loggedOutputs = logs
    .filter(log => log.capabilityId === capabilityId && log.agentId === agentId)
    .flatMap(log => {
      const outputTitle =
        typeof log.metadata?.outputTitle === 'string' ? log.metadata.outputTitle : undefined;
      const outputSummary =
        typeof log.metadata?.outputSummary === 'string'
          ? log.metadata.outputSummary
          : undefined;

      if (!outputTitle && !outputSummary) {
        return [];
      }

      return [
        {
          id: `${log.id}-OUT`,
          title: outputTitle || 'Capability response',
          summary: outputSummary || log.message,
          timestamp: log.timestamp,
          status:
            log.metadata?.outputStatus === 'pending' ? 'pending' : 'completed',
          artifactId:
            typeof log.metadata?.artifactId === 'string' ? log.metadata.artifactId : undefined,
        } satisfies AgentOutputRecord,
      ];
    });

  return [...loggedOutputs, ...taskOutputs];
};

export const buildAgentUsage = (
  capabilityId: string,
  agentId: string,
  tasks: AgentTask[] = AGENT_TASKS,
  logs: ExecutionLog[] = EXECUTION_LOGS,
) => {
  const relatedTasks = tasks.filter(
    task => task.capabilityId === capabilityId && task.agent === agentId,
  );
  const relatedLogs = logs.filter(
    log => log.capabilityId === capabilityId && log.agentId === agentId,
  );
  const logsWithUsage = relatedLogs.filter(log =>
    getMetadataNumber(log.metadata?.totalTokens) !== undefined ||
    getMetadataNumber(log.metadata?.promptTokens) !== undefined ||
    getMetadataNumber(log.metadata?.completionTokens) !== undefined,
  );
  const logsWithoutUsageCount = relatedLogs.length - logsWithUsage.length;
  const taskPromptTokens = relatedTasks.reduce(
    (count, task) => count + Math.max(320, (task.prompt || '').length * 2),
    0,
  );
  const taskCompletionTokens = relatedTasks.reduce(
    (count, task) => count + (task.producedOutputs?.length || 0) * 280 + 160,
    0,
  );
  const promptTokens =
    taskPromptTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.promptTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 48;
  const completionTokens =
    taskCompletionTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.completionTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 36;
  const totalTokens = promptTokens + completionTokens;
  const requestCount =
    logsWithUsage.length > 0
      ? relatedTasks.length + logsWithUsage.length
      : Math.max(relatedLogs.length, relatedTasks.length);

  return {
    requestCount,
    promptTokens,
    completionTokens,
    totalTokens,
    estimatedCostUsd: Number((totalTokens * 0.000003).toFixed(4)),
    lastRunAt: relatedLogs[relatedLogs.length - 1]?.timestamp || relatedTasks[0]?.timestamp,
  };
};

export const applyWorkspaceRuntime = (
  capability: Capability,
  agents: CapabilityAgent[],
  tasks: AgentTask[],
  logs: ExecutionLog[],
): CapabilityAgent[] =>
  agents.map(agent => ({
    ...agent,
    capabilityId: capability.id,
    skillIds: agent.skillIds?.length ? agent.skillIds : getDefaultSkillIds(capability),
    provider: agent.provider || DEFAULT_AGENT_PROVIDER,
    model: agent.model || DEFAULT_AGENT_MODEL,
    tokenLimit: agent.tokenLimit || DEFAULT_AGENT_TOKEN_LIMIT,
    usage: buildAgentUsage(capability.id, agent.id, tasks, logs),
    previousOutputs: buildPreviousOutputs(capability.id, agent.id, tasks, logs),
  }));

export const buildOwnerAgent = (capability: Capability): CapabilityAgent => {
  const ownerAgentId =
    capability.specialAgentId ||
    `AGENT-${slugify(capability.name || capability.id || 'CAPABILITY')}-OWNER`;

  return {
    id: ownerAgentId,
    capabilityId: capability.id,
    name: 'Capability Owning Agent',
    role: 'Capability Owner',
    objective: `Own the end-to-end delivery context for ${capability.name} and coordinate all downstream agents within this capability.`,
    systemPrompt: `You are the capability owner for ${capability.name}. Ground every decision, workflow, and team action in the capability's domain, documentation, and governance context.`,
    initializationStatus: 'READY',
    documentationSources: getCapabilityDocumentationSources(capability),
    inputArtifacts: ['Capability charter'],
    outputArtifacts: ['Capability operating model'],
    isOwner: true,
    learningNotes: [
      `${capability.name} team context is isolated to this capability.`,
      `All downstream chats, agents, and workflows should remain aligned to ${capability.domain || capability.name}.`,
    ],
    skillIds: getDefaultSkillIds(capability),
    provider: DEFAULT_AGENT_PROVIDER,
    model: DEFAULT_AGENT_MODEL,
    tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
    usage: buildAgentUsage(capability.id, ownerAgentId, [], []),
    previousOutputs: [],
  };
};

export const buildWelcomeMessage = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityChatMessage => ({
  id: `MSG-${capability.id}-WELCOME`,
  capabilityId: capability.id,
  role: 'agent',
  content: `I am the Capability Owning Agent for ${capability.name}. Everything in this workspace now belongs to this capability context, including team formation, learning, workflows, and chat.`,
  timestamp: 'Just now',
  agentId: ownerAgent.id,
  agentName: ownerAgent.name,
});

export const buildSeededAgents = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityAgent[] => {
  const nextAgents = new Map<string, CapabilityAgent>();
  const learningByAgent = LEARNING_UPDATES.filter(
    update => update.capabilityId === capability.id,
  ).reduce<Record<string, string[]>>((acc, update) => {
    acc[update.agentId] = [...(acc[update.agentId] || []), update.insight];
    return acc;
  }, {});

  const registerAgent = (agentId?: string | null, role = 'Capability Agent') => {
    if (!agentId || agentId === ownerAgent.id || nextAgents.has(agentId)) {
      return;
    }

    const outputArtifacts = ARTIFACTS.filter(
      artifact =>
        artifact.capabilityId === capability.id &&
        (artifact.connectedAgentId === agentId || artifact.agent === agentId),
    ).map(artifact => artifact.name);

    nextAgents.set(agentId, {
      id: agentId,
      capabilityId: capability.id,
      name: toAgentLabel(agentId),
      role,
      objective: `Execute ${capability.name} work inside this capability context and hand off outputs to the next workflow stage.`,
      systemPrompt: `You are a ${role.toLowerCase()} for ${capability.name}. Stay inside this capability's metadata, documentation, workflows, and learning context.`,
      initializationStatus: 'READY',
      documentationSources: getCapabilityDocumentationSources(capability),
      inputArtifacts: [],
      outputArtifacts,
      learningNotes: learningByAgent[agentId] || [],
      skillIds: getDefaultSkillIds(capability),
      provider: DEFAULT_AGENT_PROVIDER,
      model: DEFAULT_AGENT_MODEL,
      tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
      usage: buildAgentUsage(capability.id, agentId),
      previousOutputs: buildPreviousOutputs(capability.id, agentId),
    });
  };

  WORKFLOWS.filter(workflow => workflow.capabilityId === capability.id).forEach(workflow => {
    workflow.steps.forEach(step => registerAgent(step.agentId, 'Workflow Agent'));
  });
  AGENT_TASKS.filter(task => task.capabilityId === capability.id).forEach(task =>
    registerAgent(task.agent, 'Task Agent'),
  );
  ARTIFACTS.filter(artifact => artifact.capabilityId === capability.id).forEach(artifact =>
    registerAgent(artifact.connectedAgentId || artifact.agent, 'Artifact Agent'),
  );
  WORK_ITEMS.filter(item => item.capabilityId === capability.id).forEach(item =>
    registerAgent(item.assignedAgentId, 'Delivery Agent'),
  );
  EXECUTION_LOGS.filter(log => log.capabilityId === capability.id).forEach(log =>
    registerAgent(log.agentId, 'Execution Agent'),
  );

  return [ownerAgent, ...nextAgents.values()];
};

export const materializeWorkspace = (
  capability: Capability,
  workspace: {
    capabilityId: string;
    agents: CapabilityAgent[];
    workflows: Workflow[];
    artifacts: CapabilityWorkspace['artifacts'];
    tasks: AgentTask[];
    executionLogs: ExecutionLog[];
    learningUpdates: LearningUpdate[];
    workItems: WorkItem[];
    messages: CapabilityChatMessage[];
    activeChatAgentId?: string;
    createdAt: string;
  },
): CapabilityWorkspace => {
  const ownerAgent = workspace.agents.find(agent => agent.isOwner) || buildOwnerAgent(capability);
  const agents = applyWorkspaceRuntime(
    capability,
    [ownerAgent, ...workspace.agents.filter(agent => !agent.isOwner && agent.id !== ownerAgent.id)],
    workspace.tasks,
    workspace.executionLogs,
  );

  return {
    capabilityId: capability.id,
    agents,
    workflows: workspace.workflows,
    artifacts: workspace.artifacts,
    tasks: workspace.tasks,
    executionLogs: workspace.executionLogs,
    learningUpdates: workspace.learningUpdates,
    workItems: workspace.workItems,
    messages:
      workspace.messages.length > 0
        ? workspace.messages
        : [buildWelcomeMessage(capability, ownerAgent)],
    activeChatAgentId:
      workspace.activeChatAgentId &&
      agents.some(agent => agent.id === workspace.activeChatAgentId)
        ? workspace.activeChatAgentId
        : ownerAgent.id,
    createdAt: workspace.createdAt,
  };
};
