import React, { createContext, ReactNode, useContext, useEffect, useRef, useState } from 'react';
import {
  AgentOutputRecord,
  AgentUsage,
  Capability,
  CapabilityAgent,
  CapabilityChatMessage,
  CapabilityWorkspace,
  Skill,
} from '../types';
import {
  AGENT_TASKS,
  ARTIFACTS,
  CAPABILITIES,
  COPILOT_MODEL_OPTIONS,
  EXECUTION_LOGS,
  LEARNING_UPDATES,
  WORKFLOWS,
  WORK_ITEMS,
} from '../constants';
import {
  addCapabilityAgentRecord,
  addCapabilitySkillRecord,
  appendCapabilityMessageRecord,
  createCapabilityRecord,
  fetchAppState,
  replaceCapabilityWorkspaceContentRecord,
  removeCapabilitySkillRecord,
  setActiveChatAgentRecord,
  updateCapabilityAgentRecord,
  updateCapabilityRecord,
  type AppState,
} from '../lib/api';

interface CapabilityContextType {
  activeCapability: Capability;
  setActiveCapability: (capability: Capability) => void;
  capabilities: Capability[];
  capabilityWorkspaces: CapabilityWorkspace[];
  addCapability: (capability: Capability) => void;
  createCapability: (capability: Capability) => void;
  getCapabilityWorkspace: (capabilityId: string) => CapabilityWorkspace;
  updateCapabilityMetadata: (capabilityId: string, updates: Partial<Capability>) => void;
  addCapabilitySkill: (capabilityId: string, skill: Skill) => void;
  removeCapabilitySkill: (capabilityId: string, skillId: string) => void;
  addCapabilityAgent: (
    capabilityId: string,
    agent: Omit<CapabilityAgent, 'capabilityId'>,
  ) => void;
  updateCapabilityAgent: (
    capabilityId: string,
    agentId: string,
    updates: Partial<CapabilityAgent>,
  ) => void;
  appendCapabilityMessage: (
    capabilityId: string,
    message: Omit<CapabilityChatMessage, 'capabilityId'>,
  ) => void;
  setActiveChatAgent: (capabilityId: string, agentId: string) => void;
  setCapabilityWorkspaceContent: (
    capabilityId: string,
    updates: Partial<
      Pick<
        CapabilityWorkspace,
        'workflows' | 'artifacts' | 'tasks' | 'executionLogs' | 'learningUpdates' | 'workItems'
      >
    >,
  ) => void;
}

const CapabilityContext = createContext<CapabilityContextType | undefined>(undefined);
const SEEDED_CAPABILITY_IDS = new Set(CAPABILITIES.map(capability => capability.id));
const DEFAULT_AGENT_PROVIDER = 'GitHub Copilot API' as const;
const DEFAULT_AGENT_MODEL = COPILOT_MODEL_OPTIONS[0].id;
const DEFAULT_AGENT_TOKEN_LIMIT = 12000;

const slugify = (value: string) =>
  value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 24);

const getCapabilityDocumentationSources = (capability: Capability) =>
  [capability.confluenceLink, capability.jiraBoardLink, capability.documentationNotes].filter(
    Boolean,
  ) as string[];

const toAgentLabel = (value: string) =>
  value
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, char => char.toUpperCase());

const getDefaultSkillIds = (capability: Capability) =>
  capability.skillLibrary.map(skill => skill.id);

const getMetadataNumber = (value: unknown) =>
  typeof value === 'number' && Number.isFinite(value) ? value : undefined;

const buildPreviousOutputs = (
  capabilityId: string,
  agentId: string,
  tasks: CapabilityWorkspace['tasks'] = AGENT_TASKS,
  logs: CapabilityWorkspace['executionLogs'] = EXECUTION_LOGS,
): AgentOutputRecord[] => {
  const taskOutputs = tasks
    .filter(task => task.capabilityId === capabilityId && task.agent === agentId)
    .flatMap(task =>
      (task.producedOutputs || []).map((output, index) => ({
        id: `${task.id}-OUT-${index + 1}`,
        title: output.name,
        summary: `${task.title} output generated by ${toAgentLabel(agentId)}.`,
        timestamp: task.timestamp,
        status: output.status,
        relatedTaskId: task.id,
      })),
    );

  const loggedOutputs = logs
    .filter(log => log.capabilityId === capabilityId && log.agentId === agentId)
    .flatMap(log => {
      const outputTitle =
        typeof log.metadata?.outputTitle === 'string' ? log.metadata.outputTitle : undefined;
      const outputSummary =
        typeof log.metadata?.outputSummary === 'string'
          ? log.metadata.outputSummary
          : undefined;

      if (!outputTitle && !outputSummary) {
        return [];
      }

      return [
        {
          id: `${log.id}-OUT`,
          title: outputTitle || 'Capability response',
          summary: outputSummary || log.message,
          timestamp: log.timestamp,
          status:
            log.metadata?.outputStatus === 'pending' ? 'pending' : 'completed',
          artifactId:
            typeof log.metadata?.artifactId === 'string' ? log.metadata.artifactId : undefined,
        } satisfies AgentOutputRecord,
      ];
    });

  return [...loggedOutputs, ...taskOutputs];
};

const buildAgentUsage = (
  capabilityId: string,
  agentId: string,
  tasks: CapabilityWorkspace['tasks'] = AGENT_TASKS,
  logs: CapabilityWorkspace['executionLogs'] = EXECUTION_LOGS,
): AgentUsage => {
  const relatedTasks = tasks.filter(
    task => task.capabilityId === capabilityId && task.agent === agentId,
  );
  const relatedLogs = logs.filter(
    log => log.capabilityId === capabilityId && log.agentId === agentId,
  );
  const logsWithUsage = relatedLogs.filter(log =>
    getMetadataNumber(log.metadata?.totalTokens) !== undefined ||
    getMetadataNumber(log.metadata?.promptTokens) !== undefined ||
    getMetadataNumber(log.metadata?.completionTokens) !== undefined,
  );
  const logsWithoutUsageCount = relatedLogs.length - logsWithUsage.length;
  const taskPromptTokens = relatedTasks.reduce(
    (count, task) => count + Math.max(320, (task.prompt || '').length * 2),
    0,
  );
  const taskCompletionTokens = relatedTasks.reduce(
    (count, task) => count + (task.producedOutputs?.length || 0) * 280 + 160,
    0,
  );
  const promptTokens =
    taskPromptTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.promptTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 48;
  const completionTokens =
    taskCompletionTokens +
    logsWithUsage.reduce(
      (count, log) => count + (getMetadataNumber(log.metadata?.completionTokens) || 0),
      0,
    ) +
    logsWithoutUsageCount * 36;
  const totalTokens = promptTokens + completionTokens;
  const requestCount =
    logsWithUsage.length > 0
      ? relatedTasks.length + logsWithUsage.length
      : Math.max(relatedLogs.length, relatedTasks.length);

  return {
    requestCount,
    promptTokens,
    completionTokens,
    totalTokens,
    estimatedCostUsd: Number((totalTokens * 0.000003).toFixed(4)),
    lastRunAt: relatedLogs[relatedLogs.length - 1]?.timestamp || relatedTasks[0]?.timestamp,
  };
};

const withAgentDefaults = (
  capability: Capability,
  agent: CapabilityAgent,
  workspaceContent?: Pick<CapabilityWorkspace, 'tasks' | 'executionLogs'>,
): CapabilityAgent => ({
  ...agent,
  capabilityId: capability.id,
  skillIds: agent.skillIds?.length ? agent.skillIds : getDefaultSkillIds(capability),
  provider: agent.provider || DEFAULT_AGENT_PROVIDER,
  model: agent.model || DEFAULT_AGENT_MODEL,
  tokenLimit: agent.tokenLimit || DEFAULT_AGENT_TOKEN_LIMIT,
  usage:
    workspaceContent
      ? buildAgentUsage(
          capability.id,
          agent.id,
          workspaceContent.tasks,
          workspaceContent.executionLogs,
        )
      : agent.usage ||
        buildAgentUsage(
          capability.id,
          agent.id,
          workspaceContent?.tasks,
          workspaceContent?.executionLogs,
        ),
  previousOutputs:
    workspaceContent
      ? buildPreviousOutputs(
          capability.id,
          agent.id,
          workspaceContent.tasks,
          workspaceContent.executionLogs,
        )
      : agent.previousOutputs !== undefined
      ? agent.previousOutputs
      : buildPreviousOutputs(
          capability.id,
          agent.id,
          workspaceContent?.tasks,
          workspaceContent?.executionLogs,
        ),
});

const buildOwnerAgent = (capability: Capability): CapabilityAgent => {
  const ownerAgentId =
    capability.specialAgentId || `AGENT-${slugify(capability.name || capability.id || 'CAPABILITY')}-OWNER`;

  return {
    id: ownerAgentId,
    capabilityId: capability.id,
    name: 'Capability Owning Agent',
    role: 'Capability Owner',
    objective: `Own the end-to-end delivery context for ${capability.name} and coordinate all downstream agents within this capability.`,
    systemPrompt: `You are the capability owner for ${capability.name}. Ground every decision, workflow, and team action in the capability's domain, documentation, and governance context.`,
    initializationStatus: 'READY',
    documentationSources: getCapabilityDocumentationSources(capability),
    inputArtifacts: ['Capability charter'],
    outputArtifacts: ['Capability operating model'],
    isOwner: true,
    learningNotes: [
      `${capability.name} team context is isolated to this capability.`,
      `All downstream chats, agents, and workflows should remain aligned to ${capability.domain || capability.name}.`,
    ],
    skillIds: getDefaultSkillIds(capability),
    provider: DEFAULT_AGENT_PROVIDER,
    model: DEFAULT_AGENT_MODEL,
    tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
    usage: buildAgentUsage(capability.id, ownerAgentId),
    previousOutputs: buildPreviousOutputs(capability.id, ownerAgentId),
  };
};

const buildWelcomeMessage = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityChatMessage => ({
  id: `MSG-${capability.id}-WELCOME`,
  capabilityId: capability.id,
  role: 'agent',
  content: `I am the Capability Owning Agent for ${capability.name}. Everything in this workspace now belongs to this capability context, including team formation, learning, workflows, and chat.`,
  timestamp: 'Just now',
  agentId: ownerAgent.id,
  agentName: ownerAgent.name,
});

const buildSeededAgents = (
  capability: Capability,
  ownerAgent: CapabilityAgent,
): CapabilityAgent[] => {
  const nextAgents = new Map<string, CapabilityAgent>();
  const learningByAgent = LEARNING_UPDATES.filter(update => update.capabilityId === capability.id).reduce<
    Record<string, string[]>
  >((acc, update) => {
    acc[update.agentId] = [...(acc[update.agentId] || []), update.insight];
    return acc;
  }, {});

  const registerAgent = (agentId?: string | null, role = 'Capability Agent') => {
    if (!agentId || agentId === ownerAgent.id || nextAgents.has(agentId)) {
      return;
    }

    const outputArtifacts = ARTIFACTS.filter(
      artifact =>
        artifact.capabilityId === capability.id &&
        (artifact.connectedAgentId === agentId || artifact.agent === agentId),
    ).map(artifact => artifact.name);

    nextAgents.set(agentId, {
      id: agentId,
      capabilityId: capability.id,
      name: toAgentLabel(agentId),
      role,
      objective: `Execute ${capability.name} work inside this capability context and hand off outputs to the next workflow stage.`,
      systemPrompt: `You are a ${role.toLowerCase()} for ${capability.name}. Stay inside this capability's metadata, documentation, workflows, and learning context.`,
      initializationStatus: 'READY',
      documentationSources: getCapabilityDocumentationSources(capability),
      inputArtifacts: [],
      outputArtifacts,
      learningNotes: learningByAgent[agentId] || [],
      skillIds: getDefaultSkillIds(capability),
      provider: DEFAULT_AGENT_PROVIDER,
      model: DEFAULT_AGENT_MODEL,
      tokenLimit: DEFAULT_AGENT_TOKEN_LIMIT,
      usage: buildAgentUsage(capability.id, agentId),
      previousOutputs: buildPreviousOutputs(capability.id, agentId),
    });
  };

  WORKFLOWS.filter(workflow => workflow.capabilityId === capability.id).forEach(workflow => {
    workflow.steps.forEach(step => registerAgent(step.agentId, 'Workflow Agent'));
  });
  AGENT_TASKS.filter(task => task.capabilityId === capability.id).forEach(task =>
    registerAgent(task.agent, 'Task Agent'),
  );
  ARTIFACTS.filter(artifact => artifact.capabilityId === capability.id).forEach(artifact =>
    registerAgent(artifact.connectedAgentId || artifact.agent, 'Artifact Agent'),
  );
  WORK_ITEMS.filter(item => item.capabilityId === capability.id).forEach(item =>
    registerAgent(item.assignedAgentId, 'Delivery Agent'),
  );
  EXECUTION_LOGS.filter(log => log.capabilityId === capability.id).forEach(log =>
    registerAgent(log.agentId, 'Execution Agent'),
  );

  return [ownerAgent, ...nextAgents.values()];
};

const buildCapabilityWorkspace = (
  capability: Capability,
  includeSeedData = false,
): CapabilityWorkspace => {
  const ownerAgent = buildOwnerAgent(capability);
  return {
    capabilityId: capability.id,
    agents: includeSeedData ? buildSeededAgents(capability, ownerAgent) : [ownerAgent],
    workflows: includeSeedData
      ? WORKFLOWS.filter(workflow => workflow.capabilityId === capability.id)
      : [],
    artifacts: includeSeedData
      ? ARTIFACTS.filter(artifact => artifact.capabilityId === capability.id)
      : [],
    tasks: includeSeedData ? AGENT_TASKS.filter(task => task.capabilityId === capability.id) : [],
    executionLogs: includeSeedData
      ? EXECUTION_LOGS.filter(log => log.capabilityId === capability.id)
      : [],
    learningUpdates: includeSeedData
      ? LEARNING_UPDATES.filter(update => update.capabilityId === capability.id)
      : [],
    workItems: includeSeedData ? WORK_ITEMS.filter(item => item.capabilityId === capability.id) : [],
    messages: [buildWelcomeMessage(capability, ownerAgent)],
    activeChatAgentId: ownerAgent.id,
    createdAt: new Date().toISOString(),
  };
};

const upsertCapability = (items: Capability[], next: Capability) =>
  items.some(item => item.id === next.id)
    ? items.map(item => (item.id === next.id ? next : item))
    : [...items, next];

const upsertWorkspace = (items: CapabilityWorkspace[], next: CapabilityWorkspace) =>
  items.some(item => item.capabilityId === next.capabilityId)
    ? items.map(item => (item.capabilityId === next.capabilityId ? next : item))
    : [...items, next];

const mergeCapabilities = (persistedCapabilities: Capability[]) =>
  persistedCapabilities.reduce(
    (items, capability) => upsertCapability(items, capability),
    [...CAPABILITIES],
  );

const upsertCapabilitySkill = (skills: Skill[], nextSkill: Skill) =>
  skills.some(skill => skill.id === nextSkill.id)
    ? skills.map(skill => (skill.id === nextSkill.id ? nextSkill : skill))
    : [...skills, nextSkill];

const normalizeWorkspace = (
  capability: Capability,
  workspace?: Partial<CapabilityWorkspace>,
): CapabilityWorkspace => {
  const seededWorkspace = buildCapabilityWorkspace(
    capability,
    SEEDED_CAPABILITY_IDS.has(capability.id),
  );
  const existingOwnerAgent = workspace?.agents?.find(agent => agent.isOwner);
  const nextOwnerAgent = {
    ...(existingOwnerAgent || seededWorkspace.agents[0]),
    ...buildOwnerAgent(capability),
    capabilityId: capability.id,
    isOwner: true,
  };
  const nextMessages =
    workspace?.messages?.length && workspace.messages.some(message => message.capabilityId === capability.id)
      ? workspace.messages.map(message => ({
          ...message,
          capabilityId: capability.id,
        }))
      : seededWorkspace.messages;
  const nextTasks = workspace?.tasks || seededWorkspace.tasks;
  const nextExecutionLogs = workspace?.executionLogs || seededWorkspace.executionLogs;

  return {
    ...seededWorkspace,
    ...workspace,
    capabilityId: capability.id,
    agents: [
      nextOwnerAgent,
      ...(workspace?.agents || seededWorkspace.agents).filter(
        agent => !agent.isOwner && agent.id !== nextOwnerAgent.id,
      ),
    ].map(agent =>
      withAgentDefaults(capability, agent, {
        tasks: nextTasks,
        executionLogs: nextExecutionLogs,
      }),
    ),
    workflows: workspace?.workflows || seededWorkspace.workflows,
    artifacts: workspace?.artifacts || seededWorkspace.artifacts,
    tasks: nextTasks,
    executionLogs: nextExecutionLogs,
    learningUpdates: workspace?.learningUpdates || seededWorkspace.learningUpdates,
    workItems: workspace?.workItems || seededWorkspace.workItems,
    messages: nextMessages,
    activeChatAgentId:
      workspace?.activeChatAgentId &&
      workspace.agents?.some(agent => agent.id === workspace.activeChatAgentId)
        ? workspace.activeChatAgentId
        : nextOwnerAgent.id,
    createdAt: workspace?.createdAt || seededWorkspace.createdAt,
  };
};

const readInitialState = () => {
  const capabilities = [...CAPABILITIES];

  return {
    capabilities,
    activeCapability: capabilities[0],
    capabilityWorkspaces: capabilities.map(capability =>
      buildCapabilityWorkspace(capability, true),
    ),
  };
};

const normalizeAppState = (
  state: Partial<AppState>,
  preferredActiveCapabilityId?: string,
) => {
  const nextCapabilities = mergeCapabilities(state.capabilities || []);
  const nextWorkspaces = nextCapabilities.map(capability =>
    normalizeWorkspace(
      capability,
      state.capabilityWorkspaces?.find(
        workspace => workspace.capabilityId === capability.id,
      ),
    ),
  );
  const nextActiveCapability =
    nextCapabilities.find(
      capability => capability.id === preferredActiveCapabilityId,
    ) || nextCapabilities[0];

  return {
    capabilities: nextCapabilities,
    activeCapability: nextActiveCapability,
    capabilityWorkspaces: nextWorkspaces,
  };
};

export const CapabilityProvider = ({ children }: { children: ReactNode }) => {
  const initialState = useRef(readInitialState()).current;
  const [capabilities, setCapabilities] = useState<Capability[]>(initialState.capabilities);
  const [activeCapability, setActiveCapability] = useState<Capability>(initialState.activeCapability);
  const [capabilityWorkspaces, setCapabilityWorkspaces] = useState<CapabilityWorkspace[]>(
    initialState.capabilityWorkspaces,
  );
  const mutationQueueRef = useRef<Record<string, Promise<unknown>>>({});

  useEffect(() => {
    let isMounted = true;

    fetchAppState()
      .then(state => {
        if (!isMounted) {
          return;
        }

        const nextState = normalizeAppState(state);
        setCapabilities(nextState.capabilities);
        setCapabilityWorkspaces(nextState.capabilityWorkspaces);
        setActiveCapability(current =>
          nextState.capabilities.find(capability => capability.id === current.id) ||
          nextState.activeCapability,
        );
      })
      .catch(error => {
        console.warn('Failed to hydrate capability state from the API.', error);
      });

    return () => {
      isMounted = false;
    };
  }, []);

  const queueCapabilityMutation = (
    capabilityId: string,
    mutation: () => Promise<unknown>,
  ) => {
    const previousMutation = mutationQueueRef.current[capabilityId] || Promise.resolve();
    const nextMutation = previousMutation.catch(() => undefined).then(mutation);
    mutationQueueRef.current[capabilityId] = nextMutation.catch(() => undefined);
    return nextMutation;
  };

  const getCapabilityById = (capabilityId: string) =>
    capabilities.find(capability => capability.id === capabilityId) ||
    CAPABILITIES.find(capability => capability.id === capabilityId) ||
    activeCapability;

  const getCapabilityWorkspace = (capabilityId: string) => {
    const existingWorkspace = capabilityWorkspaces.find(
      workspace => workspace.capabilityId === capabilityId,
    );
    if (existingWorkspace) {
      return existingWorkspace;
    }
    return buildCapabilityWorkspace(
      getCapabilityById(capabilityId),
      SEEDED_CAPABILITY_IDS.has(capabilityId),
    );
  };

  const logMutationFailure = (scope: string, error: unknown) => {
    console.warn(
      `Failed to sync ${scope} with the capability persistence API.`,
      error,
    );
  };

  const addCapability = (newCapability: Capability) => {
    setCapabilities(prev => upsertCapability(prev, newCapability));
    setCapabilityWorkspaces(prev =>
      prev.some(workspace => workspace.capabilityId === newCapability.id)
        ? prev
        : [...prev, buildCapabilityWorkspace(newCapability)],
    );

    void queueCapabilityMutation(newCapability.id, () =>
      createCapabilityRecord(newCapability),
    ).catch(error => {
      logMutationFailure(`capability ${newCapability.id}`, error);
    });
  };

  const createCapability = (newCapability: Capability) => {
    addCapability(newCapability);
    setActiveCapability(newCapability);
  };

  const updateCapabilityMetadata = (
    capabilityId: string,
    updates: Partial<Capability>,
  ) => {
    let updatedCapability: Capability | null = null;

    setCapabilities(prev =>
      prev.map(capability => {
        if (capability.id !== capabilityId) {
          return capability;
        }

        updatedCapability = { ...capability, ...updates };
        return updatedCapability;
      }),
    );

    setActiveCapability(prev =>
      prev.id === capabilityId ? { ...prev, ...updates } : prev,
    );

    setCapabilityWorkspaces(prev => {
      const capability = updatedCapability || getCapabilityById(capabilityId);
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      const ownerAgent = existingWorkspace.agents.find(agent => agent.isOwner);
      const nextOwnerAgent = ownerAgent
        ? {
            ...ownerAgent,
            id: capability.specialAgentId || ownerAgent.id,
            objective: `Own the end-to-end delivery context for ${capability.name} and coordinate all downstream agents within this capability.`,
            systemPrompt: `You are the capability owner for ${capability.name}. Ground every decision, workflow, and team action in the capability's domain, documentation, and governance context.`,
            documentationSources: getCapabilityDocumentationSources(capability),
            learningNotes: [
              `${capability.name} team context is isolated to this capability.`,
              `All downstream chats, agents, and workflows should remain aligned to ${capability.domain || capability.name}.`,
            ],
          }
        : buildOwnerAgent(capability);

      const remainingAgents = existingWorkspace.agents.filter(agent => !agent.isOwner);
      const nextWorkspace: CapabilityWorkspace = {
        ...existingWorkspace,
        agents: [nextOwnerAgent, ...remainingAgents].map(agent =>
          withAgentDefaults(capability, agent),
        ),
        activeChatAgentId:
          existingWorkspace.activeChatAgentId && existingWorkspace.activeChatAgentId !== ownerAgent?.id
            ? existingWorkspace.activeChatAgentId
            : nextOwnerAgent.id,
      };

      return upsertWorkspace(prev, nextWorkspace);
    });

    void queueCapabilityMutation(capabilityId, () =>
      updateCapabilityRecord(capabilityId, updates),
    ).catch(error => {
      logMutationFailure(`capability metadata for ${capabilityId}`, error);
    });
  };

  const addCapabilitySkill = (capabilityId: string, skill: Skill) => {
    let updatedCapability: Capability | null = null;

    setCapabilities(prev =>
      prev.map(capability => {
        if (capability.id !== capabilityId) {
          return capability;
        }

        updatedCapability = {
          ...capability,
          skillLibrary: upsertCapabilitySkill(capability.skillLibrary, skill),
        };
        return updatedCapability;
      }),
    );

    setActiveCapability(prev => {
      if (prev.id !== capabilityId) {
        return prev;
      }

      const nextCapability = {
        ...prev,
        skillLibrary: upsertCapabilitySkill(prev.skillLibrary, skill),
      };
      updatedCapability = nextCapability;
      return nextCapability;
    });

    setCapabilityWorkspaces(prev => {
      const capability = updatedCapability || getCapabilityById(capabilityId);
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      return upsertWorkspace(prev, {
        ...existingWorkspace,
        agents: existingWorkspace.agents.map(agent =>
          withAgentDefaults(capability, agent, {
            tasks: existingWorkspace.tasks,
            executionLogs: existingWorkspace.executionLogs,
          }),
        ),
      });
    });

    void queueCapabilityMutation(capabilityId, () =>
      addCapabilitySkillRecord(capabilityId, skill),
    ).catch(error => {
      logMutationFailure(`capability skill ${skill.id} for ${capabilityId}`, error);
    });
  };

  const removeCapabilitySkill = (capabilityId: string, skillId: string) => {
    let updatedCapability: Capability | null = null;

    setCapabilities(prev =>
      prev.map(capability => {
        if (capability.id !== capabilityId) {
          return capability;
        }

        updatedCapability = {
          ...capability,
          skillLibrary: capability.skillLibrary.filter(skill => skill.id !== skillId),
        };
        return updatedCapability;
      }),
    );

    setActiveCapability(prev => {
      if (prev.id !== capabilityId) {
        return prev;
      }

      const nextCapability = {
        ...prev,
        skillLibrary: prev.skillLibrary.filter(skill => skill.id !== skillId),
      };
      updatedCapability = nextCapability;
      return nextCapability;
    });

    setCapabilityWorkspaces(prev => {
      const capability = updatedCapability || getCapabilityById(capabilityId);
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      return upsertWorkspace(prev, {
        ...existingWorkspace,
        agents: existingWorkspace.agents.map(agent =>
          withAgentDefaults(
            capability,
            {
              ...agent,
              skillIds: agent.skillIds.filter(id => id !== skillId),
            },
            {
              tasks: existingWorkspace.tasks,
              executionLogs: existingWorkspace.executionLogs,
            },
          ),
        ),
      });
    });

    void queueCapabilityMutation(capabilityId, () =>
      removeCapabilitySkillRecord(capabilityId, skillId),
    ).catch(error => {
      logMutationFailure(`capability skill ${skillId} for ${capabilityId}`, error);
    });
  };

  const addCapabilityAgent = (
    capabilityId: string,
    agent: Omit<CapabilityAgent, 'capabilityId'>,
  ) => {
    const capability = getCapabilityById(capabilityId);

    setCapabilityWorkspaces(prev => {
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      const nextWorkspace: CapabilityWorkspace = {
        ...existingWorkspace,
        agents: [
          ...existingWorkspace.agents,
          withAgentDefaults(capability, {
            ...agent,
            capabilityId,
          }),
        ],
      };

      return upsertWorkspace(prev, nextWorkspace);
    });

    void queueCapabilityMutation(capabilityId, () =>
      addCapabilityAgentRecord(capabilityId, agent),
    ).catch(error => {
      logMutationFailure(`agent ${agent.id} for ${capabilityId}`, error);
    });
  };

  const updateCapabilityAgent = (
    capabilityId: string,
    agentId: string,
    updates: Partial<CapabilityAgent>,
  ) => {
    const capability = getCapabilityById(capabilityId);

    setCapabilityWorkspaces(prev => {
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      const nextWorkspace: CapabilityWorkspace = {
        ...existingWorkspace,
        agents: existingWorkspace.agents.map(agent =>
          agent.id === agentId ? withAgentDefaults(capability, { ...agent, ...updates }) : agent,
        ),
      };

      return upsertWorkspace(prev, nextWorkspace);
    });

    void queueCapabilityMutation(capabilityId, () =>
      updateCapabilityAgentRecord(capabilityId, agentId, updates),
    ).catch(error => {
      logMutationFailure(`agent ${agentId} for ${capabilityId}`, error);
    });
  };

  const appendCapabilityMessage = (
    capabilityId: string,
    message: Omit<CapabilityChatMessage, 'capabilityId'>,
  ) => {
    const capability = getCapabilityById(capabilityId);

    setCapabilityWorkspaces(prev => {
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      const nextWorkspace: CapabilityWorkspace = {
        ...existingWorkspace,
        messages: [
          ...existingWorkspace.messages,
          {
            ...message,
            capabilityId,
          },
        ],
      };

      return upsertWorkspace(prev, nextWorkspace);
    });

    void queueCapabilityMutation(capabilityId, () =>
      appendCapabilityMessageRecord(capabilityId, message),
    ).catch(error => {
      logMutationFailure(`chat message ${message.id} for ${capabilityId}`, error);
    });
  };

  const setActiveChatAgent = (capabilityId: string, agentId: string) => {
    const capability = getCapabilityById(capabilityId);

    setCapabilityWorkspaces(prev => {
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));

      return upsertWorkspace(prev, {
        ...existingWorkspace,
        activeChatAgentId: agentId,
      });
    });

    void queueCapabilityMutation(capabilityId, () =>
      setActiveChatAgentRecord(capabilityId, agentId),
    ).catch(error => {
      logMutationFailure(`active chat agent ${agentId} for ${capabilityId}`, error);
    });
  };

  const setCapabilityWorkspaceContent = (
    capabilityId: string,
    updates: Partial<
      Pick<
        CapabilityWorkspace,
        'workflows' | 'artifacts' | 'tasks' | 'executionLogs' | 'learningUpdates' | 'workItems'
      >
    >,
  ) => {
    const capability = getCapabilityById(capabilityId);

    setCapabilityWorkspaces(prev => {
      const existingWorkspace =
        prev.find(workspace => workspace.capabilityId === capabilityId) ||
        buildCapabilityWorkspace(capability, SEEDED_CAPABILITY_IDS.has(capabilityId));
      const draftWorkspace: CapabilityWorkspace = {
        ...existingWorkspace,
        ...updates,
      };

      return upsertWorkspace(prev, {
        ...draftWorkspace,
        agents: draftWorkspace.agents.map(agent => ({
          ...withAgentDefaults(capability, agent, {
            tasks: draftWorkspace.tasks,
            executionLogs: draftWorkspace.executionLogs,
          }),
          usage: buildAgentUsage(
            capabilityId,
            agent.id,
            draftWorkspace.tasks,
            draftWorkspace.executionLogs,
          ),
          previousOutputs: buildPreviousOutputs(
            capabilityId,
            agent.id,
            draftWorkspace.tasks,
            draftWorkspace.executionLogs,
          ),
        })),
      });
    });

    void queueCapabilityMutation(capabilityId, () =>
      replaceCapabilityWorkspaceContentRecord(capabilityId, updates),
    ).catch(error => {
      logMutationFailure(`workspace content for ${capabilityId}`, error);
    });
  };

  return (
    <CapabilityContext.Provider
      value={{
        activeCapability,
        setActiveCapability,
        capabilities,
        capabilityWorkspaces,
        addCapability,
        createCapability,
        getCapabilityWorkspace,
        updateCapabilityMetadata,
        addCapabilitySkill,
        removeCapabilitySkill,
        addCapabilityAgent,
        updateCapabilityAgent,
        appendCapabilityMessage,
        setActiveChatAgent,
        setCapabilityWorkspaceContent,
      }}
    >
      {children}
    </CapabilityContext.Provider>
  );
};

export const useCapability = () => {
  const context = useContext(CapabilityContext);
  if (context === undefined) {
    throw new Error('useCapability must be used within a CapabilityProvider');
  }
  return context;
};
